// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://meson.network",
        "contact": {
            "name": "Meson Support",
            "url": "https://meson.network",
            "email": "contact@meson.network"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/delete/:nameHash": {
            "get": {
                "description": "delete file on terminal disk",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server cmd"
                ],
                "summary": "delete file command",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0dea69026ee1c698",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sdfwefwfwfwfsdfwfwf",
                        "name": "Signature",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"hello  Razeen\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"who    are  you\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "err info",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/save": {
            "post": {
                "description": "save file from given url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server cmd"
                ],
                "summary": "save file command",
                "parameters": [
                    {
                        "description": "save command object",
                        "name": "SaveFileMsg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/meson_msg.SaveFileMsg"
                        }
                    },
                    {
                        "type": "string",
                        "description": "sdfwefwfwfwfsdfwfwf",
                        "name": "Signature",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"hello  Razeen\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"msg\": \"who    are  you\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "err info",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "meson_msg.SaveFileMsg": {
            "type": "object",
            "properties": {
                "nameHash": {
                    "type": "string"
                },
                "originUrl": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sizeLimit": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "spec-00-02-015-bchkakakbxxxxxx-019-thisisthebinddomain.mesontrackingdomain.com",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "Meson Terminal API",
	Description:      "meson terminal's api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
